"""
Documentation Timestamp Utilities for Helios Career Operations System

This module provides specialized timestamp formatting for all types of documentation
including PyDoc, Markdown, reports, and generated documents. All timestamps use
the Montreal timezone for accuracy.

Usage:
    from bmad_core.utils import get_doc_timestamp, get_doc_header
    
    # Add timestamp to any document
    timestamp = get_doc_timestamp()
    
    # Get formatted header for documents  
    header = get_doc_header("My Document Title")
"""

from datetime import datetime
import pytz
from typing import Optional
try:
    from .internet_datetime import get_current_datetime_sync
    INTERNET_TIME_AVAILABLE = True
except ImportError:
    INTERNET_TIME_AVAILABLE = False


# Montreal timezone
MONTREAL_TZ = pytz.timezone('America/Montreal')


def get_current_montreal_time() -> datetime:
    """
    Get current time in Montreal timezone using internet time sources.
    
    Returns:
        datetime: Current Montreal time
    """
    if INTERNET_TIME_AVAILABLE:
        utc_time = get_current_datetime_sync()
        # Convert UTC to Montreal time
        utc_time = utc_time.replace(tzinfo=pytz.UTC)
        return utc_time.astimezone(MONTREAL_TZ)
    else:
        # Fallback to system time with Montreal timezone
        return datetime.now(MONTREAL_TZ)


def get_doc_timestamp(format_type: str = "full") -> str:
    """
    Get formatted timestamp for documentation.
    
    Args:
        format_type: Type of formatting
            - "full": Full date and time (default)
            - "date": Date only
            - "iso": ISO format
            - "filename": Safe for filenames
            - "pydoc": PyDoc style
            
    Returns:
        str: Formatted timestamp
    """
    montreal_time = get_current_montreal_time()
    
    if format_type == "full":
        return montreal_time.strftime("%Y-%m-%d %H:%M:%S %Z")
    elif format_type == "date":
        return montreal_time.strftime("%Y-%m-%d")
    elif format_type == "iso":
        return montreal_time.isoformat()
    elif format_type == "filename":
        return montreal_time.strftime("%Y%m%d_%H%M%S")
    elif format_type == "pydoc":
        return montreal_time.strftime("%B %d, %Y at %H:%M:%S %Z")
    else:
        return montreal_time.strftime("%Y-%m-%d %H:%M:%S %Z")


def get_doc_header(title: str, author: str = "Helios Career Operations System") -> str:
    """
    Generate a standardized document header with Montreal timestamp.
    
    Args:
        title: Document title
        author: Author name (default: system name)
        
    Returns:
        str: Formatted document header
    """
    timestamp = get_doc_timestamp("full")
    return f"""
{title}
{'=' * len(title)}

Generated by: {author}
Timestamp: {timestamp}
Location: Montreal, Quebec, Canada

---
"""


def get_pydoc_timestamp() -> str:
    """
    Get timestamp specifically formatted for Python docstrings and PyDoc.
    
    Returns:
        str: PyDoc-style timestamp
    """
    return get_doc_timestamp("pydoc")


def get_markdown_timestamp() -> str:
    """
    Get timestamp for Markdown documents.
    
    Returns:
        str: Markdown-formatted timestamp
    """
    montreal_time = get_current_montreal_time()
    return f"*Generated on {montreal_time.strftime('%B %d, %Y at %H:%M:%S %Z')}*"


def get_report_header(title: str, subtitle: str = "", author: str = "HELIOS System") -> str:
    """
    Generate a comprehensive report header.
    
    Args:
        title: Report title
        subtitle: Optional subtitle
        author: Report author
        
    Returns:
        str: Formatted report header
    """
    montreal_time = get_current_montreal_time()
    timezone_info = montreal_time.strftime("%Z (UTC%z)")
    
    header = f"""
# {title}
{f'## {subtitle}' if subtitle else ''}

**Generated by:** {author}  
**Date:** {montreal_time.strftime('%A, %B %d, %Y')}  
**Time:** {montreal_time.strftime('%H:%M:%S')} {timezone_info}  
**Location:** Montreal, Quebec, Canada

---

"""
    return header


def get_filename_timestamp() -> str:
    """
    Get timestamp safe for use in filenames.
    
    Returns:
        str: Filename-safe timestamp (YYYYMMDD_HHMMSS)
    """
    return get_doc_timestamp("filename")


def format_audit_timestamp() -> str:
    """
    Get timestamp specifically for audit reports and logs.
    
    Returns:
        str: Audit-formatted timestamp
    """
    montreal_time = get_current_montreal_time()
    return montreal_time.strftime("[%Y-%m-%d %H:%M:%S %Z] AUDIT:")


def format_log_timestamp() -> str:
    """
    Get timestamp for structured logging.
    
    Returns:
        str: Log-formatted timestamp
    """
    montreal_time = get_current_montreal_time()
    return montreal_time.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3] + f" {montreal_time.strftime('%Z')}"


# Template for document generation
DOCUMENT_TEMPLATE = '''"""
{title}

{description}

Generated: {timestamp}
System: Helios Career Operations System
Location: Montreal, Quebec, Canada
Timezone: {timezone}

{content}
"""'''


def generate_document(title: str, description: str, content: str) -> str:
    """
    Generate a complete document with proper timestamp and metadata.
    
    Args:
        title: Document title
        description: Document description
        content: Main content
        
    Returns:
        str: Complete formatted document
    """
    montreal_time = get_current_montreal_time()
    
    return DOCUMENT_TEMPLATE.format(
        title=title,
        description=description,
        timestamp=montreal_time.strftime("%Y-%m-%d %H:%M:%S %Z"),
        timezone=montreal_time.strftime("%Z (UTC%z)"),
        content=content
    )